### ISSUE TITLE
Important info hidden in OpenShift console 

### ISSUE THREAD

**Issue by quintesse** [bucharest-gold/nodejs-rest-http-crud#24]
![image](https://user-images.githubusercontent.com/778793/31122222-427c827e-a83b-11e7-995c-d90564d9b88e.png)

For some reason the actual service (not the database) gets "hidden" in an "Other Resources" section, meaning that the route to access it isn't displayed by default.

Other boosters don't have this so I'm not really sure what's going on but there must be something different with this template that causes this.

**Comment by lholmquist** [comment]
hmm,  i'll check it out.

**Comment by lholmquist** [comment]
I ran the REST http booster locally yesterday on my minishift, which is at the latest version(1.6.0?) using this https://github.com/minishift/minishift-centos-iso for my image.

I am noticing that booster is under the "Other Resources" section also,  weird

**Comment by lholmquist** [comment]
ok,  so it looks like it is something in the DeploymentConfig.  in metadata: labels  it looks like i need to add an `app: PROJECT_NAME` label

**Comment by lholmquist** [comment]
@quintesse on the other crud boosters,  does the database get grouped under that other resources part?

**Comment by lholmquist** [comment]
@quintesse i updated the application.yaml to fix this i believe,   i'll cut a new tag and update the booster catalog.

I also will be updating the other node boosters since this occurs there too.

**Comment by quintesse** [comment]
> @quintesse on the other crud boosters, does the database get grouped under that other resources part?

I'm not 100% sure, but I don't think so, I think it just has a name, like "database" or something

> i updated the application.yaml ...

great! 👍
